all:
	gcc *.c ../../42cursus/libft/libft.a
	./a.out 1234
	./a.out 1234567890
	./a.out 12345678901
	./a.out 3,4
	./a.out 3.4
	./a.out 3.4.5
	./a.out 3,4,5
	./a.out "3&45"
	./a.out "3a45"
	./a.out "(3)"
	./a.out "4,3"
	./a.out asdf
	rm a.out
