NAME	=	fprime

SRC		=	main.c \
			fprime.c \

run:
		gcc -o $(NAME) $(SRC)
		./$(NAME) 225225 | cat -e
		./$(NAME) 8333325 | cat -e
		./$(NAME) 9539 | cat -e
		./$(NAME) 804577 | cat -e
		./$(NAME) 42 | cat -e
		./$(NAME) 1 | cat -e
		./$(NAME) | cat -e
		./$(NAME) 42 21 | cat -e
