NAME = hidenp

run:
	gcc -Wall -Wextra -Werror $(NAME).c -o $(NAME)
	./hidenp "fgex.;" "tyf34gdgf;'ektufjhgdgex.;.;rtjynur6" | cat -e
	./hidenp "abc" "2altrb53c.sse" | cat -e
	./hidenp "abc" "btarc" | cat -e
	./hidenp | cat -e
	rm $(NAME)

gitar:
	git add $(NAME).c
	git commit -m "autogit"
	git push

