# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ruchoa <ruchoa@student.42.rio>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/29 14:25:31 by ruchoa            #+#    #+#              #
#    Updated: 2023/07/30 15:28:12 by ruchoa           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MAKEFLAGS	= --silent

NAME		= philo

t:
			gcc pthread.c -pthread -o pthread
			./pthread
			rm pthread

p:
			gcc process.c -o process
			./process
			rm ./process
